// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRARcKWcoYHResrw4mC4img6iDmcIfsQ',
    appId: '1:603917507536:web:ca15af26a9d606969237d5',
    messagingSenderId: '603917507536',
    projectId: 'forrent-b4654',
    authDomain: 'forrent-b4654.firebaseapp.com',
    storageBucket: 'forrent-b4654.appspot.com',
    measurementId: 'G-NL6EX5F63X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMKWb0uJ9Faaj_e_tyDOAp7wEqw8IipZM',
    appId: '1:603917507536:android:2325e026218625239237d5',
    messagingSenderId: '603917507536',
    projectId: 'forrent-b4654',
    storageBucket: 'forrent-b4654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD15KE6_i5oXIsNlyT1WdR0ZrK0tQdFUxg',
    appId: '1:603917507536:ios:585b538b15bb1ff59237d5',
    messagingSenderId: '603917507536',
    projectId: 'forrent-b4654',
    storageBucket: 'forrent-b4654.appspot.com',
    iosClientId: '603917507536-h56bqgi2s84bb40vmqurhuudab90mq16.apps.googleusercontent.com',
    iosBundleId: 'com.example.forRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD15KE6_i5oXIsNlyT1WdR0ZrK0tQdFUxg',
    appId: '1:603917507536:ios:585b538b15bb1ff59237d5',
    messagingSenderId: '603917507536',
    projectId: 'forrent-b4654',
    storageBucket: 'forrent-b4654.appspot.com',
    iosClientId: '603917507536-h56bqgi2s84bb40vmqurhuudab90mq16.apps.googleusercontent.com',
    iosBundleId: 'com.example.forRent',
  );
}
